### ISSUE TITLE
Xiaomi Mi Air 2018

### ISSUE THREAD

**Issue by johnnync13** [cybsuai/Mi-Notebook-Pro-tweaks#1]
Is it possible to use on xiaomi?
I create hackintosh on this laptop.
https://github.com/johnnync13/Xiaomi-Mi-Air

**Comment by cybsuai** [comment]
Hello, I think most patches can be adopted for Mi Air 2018. Moreover, it seems that Mi Air is using same EC for coolers, so coolers patch also can be used after modification. I dont know is there same problem as with Mi Notebook Pro, where coolers kicking too often

**Comment by johnnync13** [comment]
I am on second course of Engineering Computer. I know to program but not especially on hardware, only on arm.

**Comment by johnnync13** [comment]
@cybsuai Hello, do you know how Can I remove whitelist from xiaomi mi air BIOS? I install wifi on nvme but not works...
[XMAKB3M0P120C.zip](https://github.com/cybsuai/Mi-Notebook-Pro-tweaks/files/2671960/XMAKB3M0P120C.zip)

**Comment by johnnynunez** [comment]
@cybsuai 
I'm trying to remove whitelist with spi programmer. I change some variables like BIOS GUARD, RTC and more and works great.
[MiAir.zip](https://github.com/cybsuai/Mi-Notebook-Pro-tweaks/files/2781000/MiAir.zip)

**Comment by cybsuai** [comment]
Hello, I never tried to do such thing, but I think the way you selected is correct, however the problem how to find what exactly to modify...

**Comment by johnnynunez** [comment]
Yes, It is my problem. I enabled Wifi Sar, Wifi device, RST controller on nvme but nothing works to activate m.2 wifi card.
