### ISSUE TITLE
Linux version

### ISSUE THREAD

**Issue by Ogromny** [cybsuai/Mi-Notebook-Pro-tweaks#4]
Hi,

Do you plan to do a linux version of theses flash utils ?

**Comment by cybsuai** [comment]
Hello, utilities (from Insyde corp) used for patching available only for Windows. So if you dont have Win10 but want to have coolers patch, you can boot portable Win10 from USB key and apply patch once. Then it will work everywhere.

**Comment by Ogromny** [comment]
Good idea !

Thanks
